# This file was *autogenerated* from the file compare.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_30 = Integer(30); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10)
import csv
import matplotlib.pyplot as plt
from ast import literal_eval as le


with open('oldtimings.csv', 'rb') as oldFile:
    oldtimings = csv.reader(oldFile)
    with open('newtimings.csv', 'rb') as newFile:
        newtimings = csv.reader(newFile)
        points = [(le(i[_sage_const_0 ]), le(i[_sage_const_1 ])/le(j[_sage_const_1 ])) for i, j in zip(oldtimings, newtimings)]

sizes = range(_sage_const_1 , _sage_const_30 )

plt.figure()
plt.boxplot([[i[_sage_const_1 ] for i in points if i[_sage_const_0 ] == k] for k in sizes])
plt.xlim(xmin=_sage_const_10 , xmax=_sage_const_30 )
# plt.xticks(range(10, 30, 1))
plt.savefig('plots/ratio_box_plot.png')
