# This file was *autogenerated* from the file script.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_5 = Integer(5)
import random
from sage.rings.all import ZZ, QQ
import csv
from timeit import Timer
import time


class Analysis():

    def __init__(self):
        self.cols = random.randint(_sage_const_1 , _sage_const_5 )
        self.rows = random.randint(_sage_const_1 , _sage_const_5 )
        self.A = random_matrix(QQ, self.rows, self.cols)
        self.B = random_matrix(QQ, self.rows, self.cols)
        self.game = NormalFormGame([self.A, self.B])

Game = Analysis()

lrs_timer = Timer(lambda: Game.game.obtain_Nash(algorithm='lrs'))
LCP_timer = Timer(lambda: Game.game.obtain_Nash(algorithm='LCP'))
enum_timer = Timer(lambda: Game.game.obtain_Nash(algorithm='enumeration'))
lrs_time = lrs_timer.timeit(number=_sage_const_5 )
LCP_time = LCP_timer.timeit(number=_sage_const_5 )
enum_time = enum_timer.timeit(number=_sage_const_5 )

lrs_nash = Game.game.obtain_Nash(algorithm='lrs')
LCP_nash = Game.game.obtain_Nash(algorithm='LCP')
enum_nash = Game.game.obtain_Nash(algorithm='enumeration')

date = time.strftime("%d/%m/%Y")
time = time.strftime("%H:%M:%S")
dimensions = (Game.cols, Game.rows)
matrix1 = list(Game.A)
matrix2 = list(Game.B)

data = [date, time, dimensions, matrix1, matrix2, lrs_time, LCP_time, enum_time, lrs_nash, LCP_nash, enum_nash]
print data
