# This file was *autogenerated* from the file script.sage.
from sage.all_cmdline import *   # import sage library
import random
from sage.rings.all import ZZ, QQ
import csv
from timeit import Timer
import time
import socket

N = Integer(1000)
maxmatrixsize = Integer(5)
num_bound = Integer(100)
den_bound = Integer(10)
x = -Integer(100)
y = Integer(100)
timerepetitions = Integer(5)

host = socket.gethostname()

class Analysis():

    def __init__(self):
        random.seed()
        self.cols = random.randint(Integer(2), maxmatrixsize)
        random.seed()
        self.rows = random.randint(Integer(2), maxmatrixsize)
        random.seed()
        self.ring = random.choice([ZZ, QQ])
        if self.ring == QQ:
            random.seed()
            self.A = random_matrix(QQ, self.rows, self.cols, num_bound=num_bound, den_bound=den_bound)
            random.seed()
            self.B = random_matrix(QQ, self.rows, self.cols, num_bound=num_bound, den_bound=den_bound)
        if self.ring == ZZ:
            random.seed()
            self.A = random_matrix(ZZ, self.rows, self.cols, x=x, y=y)
            random.seed()
            self.B = random_matrix(ZZ, self.rows, self.cols, x=x, y=y)

        self.game = NormalFormGame([self.A, self.B])

    #@fork
    def lrs_timing(self):
        lrs_timer = Timer(lambda: self.game.obtain_Nash(algorithm='lrs'))
        lrs_time = lrs_timer.timeit(number=timerepetitions)
        lrs_nash = self.game.obtain_Nash(algorithm='lrs')
        return lrs_time, lrs_nash

    #@fork
    def LCP_timing(self):
        LCP_timer = Timer(lambda: self.game.obtain_Nash(algorithm='LCP'))
        LCP_time = LCP_timer.timeit(number=timerepetitions)
        LCP_nash = self.game.obtain_Nash(algorithm='LCP')
        return LCP_time, LCP_nash

    #@fork
    def enum_timing(self):
        enum_timer = Timer(lambda: self.game.obtain_Nash(algorithm='enumeration'))
        enum_time = enum_timer.timeit(number=timerepetitions)
        enum_nash = self.game.obtain_Nash(algorithm='enumeration')
        return enum_time, enum_nash

    def return_data(self):

        lrs_time, lrs_nash = self.lrs_timing()
        LCP_time, LCP_nash = self.LCP_timing()
        enum_time, enum_nash = self.enum_timing()

        date = time.strftime("%d/%m/%Y")
        tim = time.strftime("%H:%M:%S")
        dimensions = (self.cols, self.rows)
        ring  = self.ring
        matrix1 = list(self.A)
        matrix2 = list(self.B)
        return [date, tim, dimensions, ring, matrix1, matrix2, lrs_time, LCP_time, enum_time, lrs_nash, LCP_nash, enum_nash, host]


@parallel
def instance(k):
    Game = Analysis()
    return Game.return_data()

r = instance([k for  k in range(N)])
for result in r:
    result = list(result[Integer(1)])
    logFile = open("log.csv", 'a')
    wr = csv.writer(logFile)
    wr.writerow(result)
    logFile.close()
